"""fix daily family faces images

Revision ID: 3601fc27855b
Revises: cef865c9ed94
Create Date: 2026-02-28 01:14:40.213393

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3601fc27855b'
down_revision: Union[str, Sequence[str], None] = 'cef865c9ed94'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('daily_family_faces_images', sa.Column('image_src', sa.String(), nullable=False))
    op.drop_constraint(op.f('daily_family_faces_images_image_path_key'), 'daily_family_faces_images', type_='unique')
    op.create_unique_constraint(None, 'daily_family_faces_images', ['image_src'])
    op.drop_column('daily_family_faces_images', 'image_path')
    op.drop_column('daily_family_faces_images', 'name')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('daily_family_faces_images', sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('daily_family_faces_images', sa.Column('image_path', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'daily_family_faces_images', type_='unique')
    op.create_unique_constraint(op.f('daily_family_faces_images_image_path_key'), 'daily_family_faces_images', ['image_path'], postgresql_nulls_not_distinct=False)
    op.drop_column('daily_family_faces_images', 'image_src')
    # ### end Alembic commands ###
