"""update daily record faces images nullable true

Revision ID: b3ff753b3cec
Revises: ec272733623c
Create Date: 2026-02-28 18:22:44.692422

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b3ff753b3cec'
down_revision: Union[str, Sequence[str], None] = 'ec272733623c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('daily_record_feces_images', 'impressions',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('daily_record_feces_images', 'impressions',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###
