"""add created_at updated_at default

Revision ID: b8fe5c4d1fd7
Revises: b3ff753b3cec
Create Date: 2026-02-28 20:30:17.538723

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b8fe5c4d1fd7'
down_revision: Union[str, Sequence[str], None] = 'b3ff753b3cec'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('daily_record_feces_images', sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False))
    op.add_column('daily_record_feces_images', sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False))
    op.add_column('families', sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False))
    op.add_column('families', sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('families', 'updated_at')
    op.drop_column('families', 'created_at')
    op.drop_column('daily_record_feces_images', 'updated_at')
    op.drop_column('daily_record_feces_images', 'created_at')
    # ### end Alembic commands ###
