"""update daily record faces images table

Revision ID: ec272733623c
Revises: 3601fc27855b
Create Date: 2026-02-28 18:16:14.679224

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ec272733623c'
down_revision: Union[str, Sequence[str], None] = '3601fc27855b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('daily_record_feces_images',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('family_id', sa.Integer(), nullable=True),
    sa.Column('image_src', sa.String(), nullable=True),
    sa.Column('color', sa.Integer(), nullable=True),
    sa.Column('has_urates', sa.Boolean(), nullable=True),
    sa.Column('wateriness', sa.Integer(), nullable=True),
    sa.Column('has_undigested_seeds', sa.Boolean(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('impressions', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['family_id'], ['families.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('image_src')
    )
    op.drop_table('daily_family_faces_images')
    op.add_column('families', sa.Column('bird_type', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('families', 'bird_type')
    op.create_table('daily_family_faces_images',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('family_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('image_src', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['family_id'], ['families.id'], name=op.f('daily_family_faces_images_family_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('daily_family_faces_images_pkey')),
    sa.UniqueConstraint('image_src', name=op.f('daily_family_faces_images_image_src_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.drop_table('daily_record_feces_images')
    # ### end Alembic commands ###
